name: CI

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build and Lint
    runs-on: ${{ matrix.os }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Toolchain
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
      - name: Cache
        uses: swatinem/rust-cache@v2
      - name: Run Check
        run: |
          set -e 

          cargo check
          cargo clippy
          cargo fmt
